env:
  DIRECTORY: distribution

name: Build for release
on: 
  workflow_dispatch: null
jobs:
  Build:
    outputs:
      created: ${{ steps.daily-version.outputs.created }}
      version: ${{ steps.daily-version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - name: Run npm installation
        run: npm ci || npm install
      - name: Run tests (duh)
        run: npm test
      - name: Create tag if necessary
        uses: fregante/daily-version-action@v1
        id: daily-version
      - name: Release with 
        uses: notlmn/release-with-changelog@v3
        if: steps.daily-version.outputs.created
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: true