env:
  DIRECTORY: distribution

name: Build for release
jobs:
  Version:
    outputs:
      created: ${{ steps.daily-version.outputs.created }}
      version: ${{ steps.daily-version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - name: install
        run: npm ci || npm install
      - run: npm test
      - uses: fregante/daily-version-action@v1
        name: Create tag if necessary
        id: daily-version
      - uses: notlmn/release-with-changelog@v3
        if: steps.daily-version.outputs.created
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: true
    Upload:
      needs: Version
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: npm install
          run: npm ci || npm install
        - name: Build the extension
          run: npm run build --if-present
        - name: Update extension’s meta
          run: >-
            npx dot-json@1 $DIRECTORY/manifest.json version ${{
            needs.Version.outputs.version }}
        - name: Push artifacts
          uses: actions/upload-artifacts@v2
          wtih:
            name: dist
            path: distribution
            retention-days: 7