env:
  DIRECTORY: distribution

name: Release

on:
  workflow_dispatch: null
  schedule:
    - cron: 0 10 * * 6

jobs:
  version:
    name: Compile a new version
    outputs:
      created: ${{ steps.daily-version.outputs.created }}
      version: ${{ steps.daily-version.outputs.version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 20

      - name: CI & install dependencies
        run: npm ci || npm install

      - name: Create tag (if necessary)
        uses: fregante/daily-version-action@v1
        id: daily-version

      - name: Release with changelog
        uses: notlmn/release-with-changelog@v3
        if: steps.daily-version.outputs.created
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: true
          commit-template: '- {title} ← {hash}'
          template: |
            ### Changelog

            *To be determined*

            ### Commits

            {commits}

            {range}

  submit:
    name: Submit to stores
    needs: version
    if: github.event_name == 'workflow_dispatch' || needs.Version.outputs.created
    strategy:
      fail-fast: false
      matrix:
        command:
          - firefox
          - chrome
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: CI & install dependencies
        run: npm ci || npm install

      - name: Build
        run: npm run build --if-present

      - name: Update extension meta
        run: >-
          npx dot-json@1 $DIRECTORY/manifest.json version ${{
          needs.version.outputs.version }}

      - name: Submit
        run: |
          case ${{ matrix.command }} in
            chrome)
              cd $DIRECTORY && npx chrome-webstore-upload-cli@1 upload --auto-publish
              ;;
            firefox)
              cd $DIRECTORY && npx web-ext-submit@5
              ;;
          esac
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
